OpenAIModel:
  model: "gpt-3.5-turbo"
  api_key: "sk-xxx"

GLMModel:
  model_url: "your_chatglm_model_url like http://xxx:xx"
  timeout: 300

common:
  book: "tests/test.pdf"
  file_format: "markdown"