OpenAIModel:
  model: "gpt-3.5-turbo"
  api_key: "your_openai_api_key"

GLMModel:
  model_url: "https://api.replicate.com/v1/models/replicate/a16z-infra/llama13b-v2-chat"
  timeout: 300

common:
  book: "tests/test.pdf"
  file_format: "markdown"