OpenAIModel:
  model: "gpt-3.5-turbo"
  api_key: "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"

GLMModel:
  model_url: "your_chatglm_model_url"
  timeout: 300

common:
  book: "tests/test.pdf"
  file_format: "markdown"